INSERT INTO TB_USUARIO(EMAIL, ENDERECO, NOME_COMPLETO, NOME_SOCIAL, OBJETIVO_PROFISSIONAL,SENHA) VALUES ('fulano@gmail.com', 'Rua Tres Alguma Coisa', 'Alguma Coisa', 'Alguma coisa', 'alguma coisa', '123456');
INSERT INTO TB_USUARIO(EMAIL, ENDERECO, NOME_COMPLETO, NOME_SOCIAL, OBJETIVO_PROFISSIONAL,SENHA) VALUES ('ciclano@gmail.com','Rua quatro Alguma Coisa', 'Alguma Coisa', 'Alguma coisa', 'alguma coisa', '123456');

INSERT INTO TB_EMPRESA(CEP,  CNPJ, EMAIL, ENDERECO, LOGRADOURO, NOME_FANTASIA, RAZAO_SOCIAL, SENHA) VALUES ('44020-555', '11.180.123/0001-50', 'ciclano@gmail.com', 'Rua Boa Alguma Coisa', 'Rua Boa Alguma Coisa', 'VAGAS CONFIDENCIA', 'VAGAS CONFIDENCIA LTDA', '123456');
INSERT INTO TB_EMPRESA(CEP,  CNPJ, EMAIL, ENDERECO, LOGRADOURO, NOME_FANTASIA, RAZAO_SOCIAL, SENHA) VALUES ('44020-555', '11.180.123/0001-50', 'ciclano@gmail.com', 'Rua quatro Alguma Coisa', 'Rua quatro Alguma Coisa', 'ALGUMA COISA E CIA', 'ALGUMA COISA E CIA LTDA', '123456');

INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 500.0, 'Total', 'Dev', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 500.0, 'Total', 'QA', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 500.0, 'Total', 'QA', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');

INSERT INTO TB_USUARIO_VAGAS  (USUARIO_ID, VAGA_ID) VALUES (1,1);
INSERT INTO TB_USUARIO_VAGAS  (USUARIO_ID, VAGA_ID) VALUES (1,2);
INSERT INTO TB_USUARIO_VAGAS  (USUARIO_ID, VAGA_ID) VALUES (2,2);

