ALTER TABLE TB_USUARIO ALTER Roles SET DEFAULT 'ROLE_USUARIO'; 
ALTER TABLE TB_EMPRESA ALTER Roles SET DEFAULT 'ROLE_EMPRESA'; 


INSERT INTO TB_USUARIO(EMAIL, ENDERECO, NOME_COMPLETO, NOME_SOCIAL, OBJETIVO_PROFISSIONAL,SENHA) VALUES ('fulano@gmail.com', 'Rua Tres Alguma Coisa', 'Alguma Coisa', 'Alguma coisa', 'alguma coisa', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO TB_USUARIO(EMAIL, ENDERECO, NOME_COMPLETO, NOME_SOCIAL, OBJETIVO_PROFISSIONAL,SENHA) VALUES ('ciclano@gmail.com','Rua quatro Alguma Coisa', 'Alguma Coisa', 'Alguma coisa', 'alguma coisa', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
--INSERT INTO TB_USUARIO(EMAIL, ENDERECO, NOME_COMPLETO, NOME_SOCIAL, OBJETIVO_PROFISSIONAL,SENHA) VALUES ('a@gmail.com','Rua quatro Alguma Coisa', 'Alguma Coisa', 'Alguma coisa', 'alguma coisa', '$2a$10$vR2GYoGLcU/1bG0g1zukfONzYSfy9x2kROxsDye8wHUQdlh0lfVIa');
--INSERT INTO TB_USUARIO(EMAIL, ENDERECO, NOME_COMPLETO, NOME_SOCIAL, OBJETIVO_PROFISSIONAL,SENHA) VALUES ('v@gmail.com','Rua quatro Alguma Coisa', 'Alguma Coisa', 'Alguma coisa', 'alguma coisa', '$2a$10$mMgh22tqk66rgY7opc5f0OscutFpBNQT48F42tRNAwtIANNPX8FGi');

INSERT INTO TB_EMPRESA(CEP,  CNPJ, EMAIL, ENDERECO, LOGRADOURO, NOME_FANTASIA, RAZAO_SOCIAL, SENHA) VALUES ('44020-555', '11.180.123/0001-50', 'ciclanoEmp@gmail.com', 'Rua Boa Alguma Coisa', 'Rua Boa Alguma Coisa', 'VAGAS CONFIDENCIA', 'VAGAS CONFIDENCIA LTDA', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO TB_EMPRESA(CEP,  CNPJ, EMAIL, ENDERECO, LOGRADOURO, NOME_FANTASIA, RAZAO_SOCIAL, SENHA) VALUES ('44020-555', '11.180.123/0001-50', 'ciclano@gmail.com', 'Rua quatro Alguma Coisa', 'Rua quatro Alguma Coisa', 'ALGUMA COISA E CIA', 'ALGUMA COISA E CIA LTDA', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 500.0, 'Total', 'Dev', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 500.0, 'Total', 'QA', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 500.0, 'Total', 'QA', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 1320.0, 'Total', 'Dev. Sênior', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 1320.0, 'Total', 'Vendedor(a)', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 1320.0, 'Total', 'Aux. Recursos humanos', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 1320.0, 'Total', 'Dev. Júnior', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,5, 1320.0, 'Total', 'Dev. Full-Stack', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,10, 1320.0, 'Total', 'Aux. administrativo', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,6, 1320.0, 'Total', 'Pintor(a)', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,7, 1320.0, 'Total', 'Jovem aprendiz', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,3, 1320.0, 'Total', 'Atendente', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,2, 1320.0, 'Total', 'Balconista', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');
INSERT INTO TB_VAGA (EMPRESA_ID, NUMERO_VAGAS, SALARIO, BENEFICIO, CARGO, CONTATO, DESCRICAO_VAGA, ENDERECO, JORNADA_TRABALHO, LOCAL, REQUISITOS ) VALUES (1,1, 1320.0, 'Total', 'Promotor(a) de vendas', '75-8884564', 'alguma coisa', 'Rua FTC', '40h', 'FTC', 'Saber algo');


INSERT INTO TB_USUARIO_VAGAS  (USUARIO_ID, VAGA_ID) VALUES (1,1);
INSERT INTO TB_USUARIO_VAGAS  (USUARIO_ID, VAGA_ID) VALUES (1,2);
INSERT INTO TB_USUARIO_VAGAS  (USUARIO_ID, VAGA_ID) VALUES (2,2);


